@define-color background #161314;
@define-color foreground #FCF9F6;
@define-color color0 #3E3B3C;
@define-color color1 #79482C;
@define-color color2 #665182;
@define-color color3 #E34A5E;
@define-color color4 #B98731;
@define-color color5 #918F99;
@define-color color6 #F5EFE5;
@define-color color7 #F2EFEA;
@define-color color8 #A9A7A3;
@define-color color9 #79482C;
@define-color color10 #665182;
@define-color color11 #E34A5E;
@define-color color12 #B98731;
@define-color color13 #918F99;
@define-color color14 #F5EFE5;
@define-color color15 #F2EFEA;
